=== jc10cfc/psimulator/bp_psi/src/data/psi.dtd
<!-- <?xml version="1.0" encoding="UTF-8" ?> -->
<!-- http://www.hitsw.com/xml_utilites/ -->

<!ELEMENT access-list ( cislo, ipA, ipAWildcard ) >

<!ELEMENT access-listy ( access-list+ ) >

<!ELEMENT accessCislo ( #PCDATA ) >

<!ELEMENT adresat ( #PCDATA ) >

<!ELEMENT brana ( #PCDATA ) >

<!ELEMENT cislo ( #PCDATA ) >

<!ELEMENT ip ( #PCDATA ) >

<!ELEMENT ipA ( #PCDATA ) >

<!ELEMENT ipAWildcard ( #PCDATA ) >

<!ELEMENT ip_forward ( #PCDATA ) >

<!ELEMENT ip_konec ( #PCDATA ) >

<!ELEMENT ip_start ( #PCDATA ) >

<!ELEMENT jmeno ( #PCDATA ) >

<!ELEMENT konfigurak ( pocitac+ ) >

<!ELEMENT mac ( #PCDATA ) >

<!ELEMENT maska ( #PCDATA ) >

<!ELEMENT maskaAdresata ( #PCDATA ) >

<!ELEMENT nahozene ( #PCDATA ) >

<!ELEMENT nat ( #PCDATA ) >

<!ELEMENT natovani ( pooly, prirazeniVice, access-listy, staticke? ) >

<!ELEMENT staticke ( in, out ) >

<!ELEMENT in ( #PCDATA ) >

<!ELEMENT out ( #PCDATA ) >

<!ELEMENT overload ( #PCDATA ) >

<!ELEMENT pJmeno ( #PCDATA ) >

<!ELEMENT pocitac ( rozhrani+, routy, ip_forward?, natovani? ) >
<!ATTLIST pocitac jmeno NMTOKEN #REQUIRED >
<!ATTLIST pocitac typ NMTOKEN #REQUIRED >

<!ELEMENT pool ( pJmeno, ip_start, ip_konec, prefix ) >

<!ELEMENT poolJmeno ( #PCDATA ) >

<!ELEMENT pooly ( pool+ ) >

<!ELEMENT port ( #PCDATA ) >

<!ELEMENT prefix ( #PCDATA ) >

<!ELEMENT pripojenoK ( #PCDATA ) >

<!ELEMENT prirazeni ( accessCislo, poolJmeno, overload ) >

<!ELEMENT prirazeniVice ( prirazeni+ ) >

<!ELEMENT routy ( zaznam? ) >

<!ELEMENT rozhrani ( jmeno, ip, maska, mac, pripojenoK, nahozene, nat? ) >

<!ELEMENT rozhraniKam ( #PCDATA ) >

<!ELEMENT zaznam ( adresat, maskaAdresata, rozhraniKam, brana? ) >

=== jc10cfc/psimulator/bp_psi/src/data/linDefProtiSobe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psi.dtd">

<konfigurak>
<port>3567</port>

<pocitac jmeno="linux1" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:05</mac>
		<pripojenoK>linux2:eth0</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.1.2</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>0</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux2" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.1.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:06</mac>
		<pripojenoK>linux1:eth0</pripojenoK>
		<nahozene>true</nahozene>
		<nat>soukrome</nat>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip>192.168.2.1</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:d3:04:06</mac>
		<pripojenoK>linux3:eth0</pripojenoK>
		<nahozene>true</nahozene>
		<nat>verejne</nat>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>192.168.1.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.2</brana>
			<rozhraniKam>eth1</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
			<pool>
				<pJmeno>ovrld</pJmeno>
				<ip_start>192.168.2.1</ip_start>
				<ip_konec>192.168.2.1</ip_konec>
				<prefix>24</prefix>
			</pool>
		</pooly>
		<prirazeniVice>
			<prirazeni>
				<accessCislo>1</accessCislo>
				<poolJmeno>ovrld</poolJmeno>
				<overload>true</overload>
			</prirazeni>
		</prirazeniVice>
		<access-listy>
			<access-list>
				<cislo>1</cislo>
				<ipA>0.0.0.0</ipA>
				<ipAWildcard>255.255.255.255</ipAWildcard>
			</access-list>
		</access-listy>
	</natovani>
</pocitac>

<pocitac jmeno="linux3" typ="linux">
	<rozhrani>
		<jmeno>eth0</jmeno>
		<ip>192.168.2.2</ip>
		<maska>255.255.255.0</maska>
		<mac>00:01:02:03:04:07</mac>
		<pripojenoK>linux2:eth1</pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<rozhrani>
		<jmeno>eth1</jmeno>
		<ip></ip>
		<maska></maska>
		<mac>00:01:02:03:0a:07</mac>
		<pripojenoK></pripojenoK>
		<nahozene>true</nahozene>
	</rozhrani>
	<routy>
		<zaznam>
			<adresat>192.168.2.0</adresat>
			<maskaAdresata>255.255.255.0</maskaAdresata>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
		<zaznam>
			<adresat>0.0.0.0</adresat>
			<maskaAdresata>0.0.0.0</maskaAdresata>
			<brana>192.168.2.1</brana>
			<rozhraniKam>eth0</rozhraniKam>
		</zaznam>
	</routy>
	<ip_forward>1</ip_forward>
	<natovani>
		<pooly>
		</pooly>
		<prirazeniVice>
		</prirazeniVice>
		<access-listy>
		</access-listy>
	</natovani>
</pocitac>

</konfigurak>
